version: '3.1'

volumes:
  db:
  ftp:

services:
  # ftp:
  #   image: stilliard/pure-ftpd
  #   ports:
  #     - '21:21'
  #     - '30000-30009:30000-30009'
  #   volumes:
  #     - 'C:/TEST:/home/ftp/'
  #     - 'C:/TEST/passwd:/etc/pure-ftpd/passwd'
  #   environment:
  #     PUBLICHOST: 'localhost'
  #     FTP_USER_NAME: ftp
  #     FTP_USER_PASS: ftp
  #     FTP_USER_HOME: /home/ftp

  # redis:
  #   image: redis:5.0.8-alpine3.11
  #   ports:
  #     - 6379:6379

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 8083:15672
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - db:/data/db
  # redis-admin:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - 8081:8081
  # mongo-admin:
  #   image: mongo-express
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  # project-gulag:
  #   image: noru/project-gulag:latest
  #   depends_on:
  #     - redis
  #     - mongo
  #     - rabbitmq
