version: '3.1'

volumes:
  db:

services:
  redis:
    image: redis:5.0.8-alpine3.11
    ports:
      - 6379:6379
  redis-admin:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 8083:15672
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  mongo-admin:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  # project-gulag:
  #   image: noru/project-gulag:latest
  #   depends_on:
  #     - redis
  #     - mongo
  #     - rabbitmq
