version: '3.1'

volumes:
  db:

services:

  redis:
    image: redis:5.0.8-alpine3.11
    ports:
      - 6379:6379

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    ports: 
      - 5672:5672

        
  redis-admin:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081

  mongo-admin:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  rabbitmq-admin:
    image: rabbitmq:management-alpine
    depends_on:
      - rabbitmq
    ports: 
      - 8083:15672

  # project-gulag:
  #   image: noru/project-gulag:latest
  #   depends_on:
  #     - redis
  #     - mongo
  #     - rabbitmq


